#!/bin/bash
# Windowsで実行する場合はGit Bashに関連付けをするか、Git Bashで直接実行してください
extensionsListFiles+=(_main.extensions.txt)
# extensionsListFiles+=(apache.extensions.txt)
# extensionsListFiles+=(cpp.extensions.txt)
extensionsListFiles+=(docker.extensions.txt)
extensionsListFiles+=(golang.extensions.txt)
# extensionsListFiles+=(java.extensions.txt)
extensionsListFiles+=(laravel.extensions.txt)
extensionsListFiles+=(markdown.extensions.txt)
# extensionsListFiles+=(minecraft.extensions.txt)
extensionsListFiles+=(mysql.extensions.txt)
# extensionsListFiles+=(pdf.extensions.txt)
extensionsListFiles+=(php.extensions.txt)
# extensionsListFiles+=(powershell.extensions.txt)
extensionsListFiles+=(python.extensions.txt)
extensionsListFiles+=(rust.extensions.txt)
extensionsListFiles+=(shellscript.extensions.txt)
# extensionsListFiles+=(sqlite.extensions.txt)
# extensionsListFiles+=(xml.extensions.txt)
